# Generated by Django 6.0.3 on 2026-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите изображение (PNG, JPG, JPEG)', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
