# Generated by Django 6.0.3 on 2026-03-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО заявителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Необязательно', max_length=254, verbose_name='Email')),
                ('company', models.CharField(help_text='Название предприятия или депо', max_length=200, verbose_name='Предприятие')),
                ('locomotive_type', models.CharField(choices=[('electric', 'Электровоз'), ('diesel', 'Тепловоз'), ('shunter', 'Маневровый локомотив'), ('passenger', 'Пассажирский локомотив'), ('freight', 'Грузовой локомотив'), ('special', 'Спецтехника')], max_length=50, verbose_name='Тип локомотива')),
                ('locomotive_model', models.CharField(max_length=100, verbose_name='Модель локомотива')),
                ('locomotive_number', models.CharField(max_length=50, verbose_name='Номер локомотива')),
                ('repair_type', models.CharField(choices=[('diagnostics', 'Техническая диагностика'), ('maintenance', 'Техническое обслуживание'), ('current', 'Текущий ремонт'), ('medium', 'Средний ремонт'), ('capital', 'Капитальный ремонт'), ('emergency', 'Аварийный ремонт')], max_length=50, verbose_name='Вид ремонта')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('urgent', models.BooleanField(default=False, verbose_name='Срочная заявка')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
                'ordering': ['-created_at'],
            },
        ),
    ]
